version: 0.2

phases:

  build:
    commands:
      - IMAGE_REPO_NAME=simple-docker-project-example
      - AWS_ACCOUNT_ID=271009710463
      - AWS_DEFAULT_REGION=ap-south-1
      - IMAGE_TAG=latest
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 271009710463.dkr.ecr.ap-south-1.amazonaws.com
      - docker build -t simple-docker-project-example .
      - docker tag simple-docker-project-example:latest 271009710463.dkr.ecr.ap-south-1.amazonaws.com/simple-docker-project-example:latest
      - docker push 271009710463.dkr.ecr.ap-south-1.amazonaws.com/simple-docker-project-example:latest 
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - echo Logging in to Amazon ECR...
      
